### ISSUE TITLE
"Download source code" popup is empty on (some?) project pages

### ISSUE THREAD

**Issue by scymtym** [RDTK/CITKat#16]
**Describe the bug**

On (some?) project pages, the "Download source code" popup does not contain any commands.

**To Reproduce**

1. Visit a project page such as https://citkat-citec.bob.ci.cit-ec.net/project/cl-serialization.protocol-buffer-master.xml

2. Click the "Download source code" button

**Expected behavior**

The popup should contain commands to clone the repository.

**Comment by nexero** [comment]
Seams like Popper.js changed their code, so this won't work anymore.

I'll re-implement this feature using the [Bootstrap `collapse`](https://getbootstrap.com/docs/4.3/components/collapse/) with a nicer look overall.
